version: "3.9"

services:
  menu_service:
    build: ./menu-service/
    container_name: menu_service
    hostname: menu_service
    depends_on: 
      - menu_postgres

  menu_postgres:
    image: postgres:14
    container_name: menu_postgres
    hostname: menu_postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=menu_database

  search_service:
    build: ./search-service/
    container_name: search_service
    hostname: search_service
