version: "3.9"

services:
# microservices

## menu_service
  menu_service:
    build: ./menu-service/
    container_name: menu_service
    hostname: menu_service
    depends_on: 
      - menu_postgres
  menu_postgres:
    image: postgres:14
    container_name: menu_postgres
    hostname: menu_postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=menu_database

## search_service
  search_service:
    build: ./search-service/
    container_name: search_service
    hostname: search_service
  search_elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.2
    container_name: search_elasticsearch
    hostname: search_elasticsearch
    ports:
      - 9200:9200
    environment:
      discovery.type: single-node
  search_redis:
    image: redis:6.2.6
    container_name: search_redis
    hostname: search_redis

# ui

## customer-webui
  customer_webui:
    build: ./customer-webui/
    container_name: customer_webui
    hostname: customer_webui


# infra

## kong
  kong:
    image: kong:2.6.0-alpine
    container_name: kong
    hostname: kong
    environment:
      KONG_DATABASE: 'off'
      KONG_PROXY_ACCESS_LOG: '/dev/stdout'
      KONG_ADMIN_ACCESS_LOG: '/dev/stdout'
      KONG_PROXY_ERROR_LOG: '/dev/stderr'
      KONG_ADMIN_ERROR_LOG: '/dev/stderr'
      KONG_ADMIN_LISTEN: "0.0.0.0:8001"
      KONG_DECLARATIVE_CONFIG: "/opt/kong/kong.yaml"
    command: "kong start"
    ports:
      - 8000:8000
      - 8001:8001
    volumes:
      - ./kong.yaml:/opt/kong/kong.yaml

## kafka
  kafka:
    image: confluentinc/cp-kafka:5.2.5
    container_name: kafka
    hostname: kafka
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  zookeeper:
    image: confluentinc/cp-zookeeper:5.2.5
    container_name: zookeeper
    hostname: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
